# Generated by Django 6.0.6 on 2026-06-13 19:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator_promotion_threshold', models.PositiveIntegerField(blank=True, help_text='Accepted submissions needed to become a Database Collaborator. Must be set; reading it while unset raises an error.', null=True)),
                ('founder_threshold', models.PositiveIntegerField(blank=True, help_text='Accepted submissions needed for Community Founder (spec suggests 30). Must be set; reading it while unset raises an error.', null=True)),
                ('founder_level_achievable', models.BooleanField(default=True)),
                ('topic_proposals_enabled', models.BooleanField(default=True)),
                ('topic_proposal_voting_days', models.PositiveIntegerField(default=7)),
                ('topic_proposal_pass_ratio', models.DecimalField(decimal_places=3, default=Decimal('0.750'), help_text='Fraction of positive votes required to accept a proposal (0–1).', max_digits=4)),
            ],
            options={
                'verbose_name': 'Site configuration',
            },
        ),
    ]
