# Generated by Django 6.0.6 on 2026-06-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='gear_acceptance_min_net_votes',
            field=models.PositiveIntegerField(default=3, help_text='Minimum net votes (upvotes − downvotes) a submission needs before it is auto-published.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='gear_acceptance_min_voters',
            field=models.PositiveIntegerField(default=3, help_text='Minimum number of distinct collaborators that must vote before a submission is auto-published.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='max_rejected_before_cooldown',
            field=models.PositiveIntegerField(default=3, help_text='Once a user exceeds this many rejected submissions they are temporarily blocked from submitting (troll guard, see PRODUCT.md).'),
        ),
    ]
