"""Tests for the catalog domain *models* (catalog/models/).

Focus areas (per assignment):
- ControlledVocabulary.save() auto-generates a slug from name.
- CatalogEntry.status defaults to UNDER_REVISION; the .published()/.under_revision()
  queryset helpers filter correctly; mark_published() flips status + stamps times.
- GearItem.__str__ == "<brand> <name>".
- GuitarModel.scale_display trims trailing zeros (single value vs multiscale range).

These exercise the abstract bases through concrete subclasses (Brand, FretMaterial,
Bridge, GuitarModel, ...) since the bases themselves are abstract.
"""

from datetime import timedelta
from decimal import Decimal

from django.test import TestCase
from django.utils import timezone

from catalog.constants import PublicationStatus
from catalog.models import (
    BodyShape,
    Bridge,
    BridgeType,
    Brand,
    Country,
    FretMaterial,
    FretboardRadius,
    GuitarModel,
    Nut,
    NutMaterial,
    Pickup,
    PickupType,
    Tuner,
)


# ---------------------------------------------------------------------------
# ControlledVocabulary.save() slug auto-generation
# ---------------------------------------------------------------------------
class ControlledVocabularySlugTests(TestCase):
    """ControlledVocabulary.save() slugifies `name` into `slug` when blank."""

    def test_slug_autogenerated_from_name_when_blank(self):
        material = FretMaterial.objects.create(name="Stainless Steel")
        self.assertEqual(material.slug, "stainless-steel")

    def test_slug_persisted_to_db(self):
        FretMaterial.objects.create(name="Nickel Silver")
        reloaded = FretMaterial.objects.get(name="Nickel Silver")
        self.assertEqual(reloaded.slug, "nickel-silver")

    def test_explicit_slug_is_not_overwritten(self):
        material = FretMaterial.objects.create(
            name="Evo Gold", slug="custom-evo"
        )
        self.assertEqual(material.slug, "custom-evo")

    def test_slug_strips_punctuation_and_lowercases(self):
        # slugify drops apostrophes/punctuation and lowercases everything.
        shape = BodyShape.objects.create(name="Flying V (Gibson's)")
        self.assertEqual(shape.slug, "flying-v-gibsons")

    def test_slug_collapses_internal_whitespace(self):
        shape = BodyShape.objects.create(name="Super   Strat")
        self.assertEqual(shape.slug, "super-strat")

    def test_slug_truncated_to_120_chars(self):
        # name is max_length=100, slug max_length=120; verify the [:120] guard
        # never produces a slug longer than the column allows.
        long_name = "A" * 100
        material = FretMaterial.objects.create(name=long_name)
        self.assertLessEqual(len(material.slug), 120)
        self.assertEqual(material.slug, "a" * 100)

    def test_slug_regenerated_on_save_when_cleared(self):
        # save() only fills slug when it's falsy, so clearing it then re-saving
        # regenerates from the (possibly new) name.
        material = FretMaterial.objects.create(name="Jumbo")
        self.assertEqual(material.slug, "jumbo")
        material.name = "Medium Jumbo"
        material.slug = ""
        material.save()
        self.assertEqual(material.slug, "medium-jumbo")

    def test_existing_slug_kept_even_when_name_changes(self):
        # If the slug is already set, changing the name must NOT silently
        # re-slug it (URLs stay stable).
        material = FretMaterial.objects.create(name="Jumbo")
        original_slug = material.slug
        material.name = "Extra Jumbo"
        material.save()
        material.refresh_from_db()
        self.assertEqual(material.slug, original_slug)

    def test_default_str_is_name(self):
        country = Country.objects.create(name="Japan")
        self.assertEqual(str(country), "Japan")

    def test_default_ordering_by_name(self):
        FretMaterial.objects.create(name="Zinc")
        FretMaterial.objects.create(name="Brass")
        FretMaterial.objects.create(name="Cobalt")
        names = list(FretMaterial.objects.values_list("name", flat=True))
        self.assertEqual(names, ["Brass", "Cobalt", "Zinc"])

    def test_radius_subclass_also_slugs(self):
        # FretboardRadius adds fields but inherits the slug behaviour.
        radius = FretboardRadius.objects.create(
            name="12 inch",
            radius_min_inches=Decimal("12.00"),
            radius_max_inches=Decimal("12.00"),
        )
        self.assertEqual(radius.slug, "12-inch")


# ---------------------------------------------------------------------------
# CatalogEntry.status default + queryset helpers + mark_published()
# ---------------------------------------------------------------------------
class CatalogEntryStatusTests(TestCase):
    """status defaults to UNDER_REVISION; published()/under_revision() filter;
    mark_published() flips status and stamps reviewed_at/published_at.

    Brand is the simplest concrete CatalogEntry, so it stands in for the base.
    """

    def test_status_defaults_to_under_revision(self):
        brand = Brand.objects.create(name="Ibanez")
        self.assertEqual(brand.status, PublicationStatus.UNDER_REVISION)
        self.assertEqual(brand.status, "under_revision")

    def test_new_entry_has_no_review_timestamps(self):
        brand = Brand.objects.create(name="Jackson")
        self.assertIsNone(brand.reviewed_at)
        self.assertIsNone(brand.published_at)

    def test_under_revision_queryset_filters_to_pending(self):
        pending = Brand.objects.create(name="Pending Brand")
        published = Brand.objects.create(
            name="Live Brand", status=PublicationStatus.PUBLISHED
        )
        rejected = Brand.objects.create(
            name="Bad Brand", status=PublicationStatus.REJECTED
        )
        result = set(Brand.objects.under_revision())
        self.assertIn(pending, result)
        self.assertNotIn(published, result)
        self.assertNotIn(rejected, result)

    def test_published_queryset_filters_to_published(self):
        pending = Brand.objects.create(name="Pending Brand")
        published = Brand.objects.create(
            name="Live Brand", status=PublicationStatus.PUBLISHED
        )
        rejected = Brand.objects.create(
            name="Bad Brand", status=PublicationStatus.REJECTED
        )
        result = set(Brand.objects.published())
        self.assertIn(published, result)
        self.assertNotIn(pending, result)
        self.assertNotIn(rejected, result)

    def test_published_excludes_rejected(self):
        Brand.objects.create(name="Rejected Co", status=PublicationStatus.REJECTED)
        self.assertEqual(Brand.objects.published().count(), 0)

    def test_published_and_under_revision_are_disjoint(self):
        Brand.objects.create(name="A", status=PublicationStatus.UNDER_REVISION)
        Brand.objects.create(name="B", status=PublicationStatus.PUBLISHED)
        Brand.objects.create(name="C", status=PublicationStatus.REJECTED)
        published_ids = set(Brand.objects.published().values_list("pk", flat=True))
        revision_ids = set(
            Brand.objects.under_revision().values_list("pk", flat=True)
        )
        self.assertEqual(published_ids & revision_ids, set())
        # The rejected row appears in neither bucket.
        self.assertEqual(len(published_ids) + len(revision_ids), 2)

    def test_queryset_helpers_chainable(self):
        # The helpers live on a QuerySet (not just the manager), so they must be
        # chainable after an ordinary filter.
        Brand.objects.create(name="Fender", status=PublicationStatus.PUBLISHED)
        Brand.objects.create(name="Squier", status=PublicationStatus.PUBLISHED)
        qs = Brand.objects.filter(name="Fender").published()
        self.assertEqual(qs.count(), 1)
        self.assertEqual(qs.first().name, "Fender")

    def test_mark_published_sets_status_and_timestamps(self):
        brand = Brand.objects.create(name="Gibson")
        before = timezone.now()
        brand.mark_published()
        after = timezone.now()

        self.assertEqual(brand.status, PublicationStatus.PUBLISHED)
        self.assertIsNotNone(brand.reviewed_at)
        self.assertIsNotNone(brand.published_at)
        # Stamps fall within the call window.
        self.assertGreaterEqual(brand.reviewed_at, before)
        self.assertLessEqual(brand.reviewed_at, after)
        self.assertGreaterEqual(brand.published_at, before)
        self.assertLessEqual(brand.published_at, after)
        # Both stamps come from the same `now`.
        self.assertEqual(brand.reviewed_at, brand.published_at)

    def test_mark_published_persists_to_db_by_default(self):
        brand = Brand.objects.create(name="ESP")
        brand.mark_published()
        reloaded = Brand.objects.get(pk=brand.pk)
        self.assertEqual(reloaded.status, PublicationStatus.PUBLISHED)
        self.assertIsNotNone(reloaded.published_at)
        self.assertIsNotNone(reloaded.reviewed_at)

    def test_mark_published_moves_entry_between_querysets(self):
        brand = Brand.objects.create(name="Schecter")
        self.assertIn(brand, Brand.objects.under_revision())
        self.assertNotIn(brand, Brand.objects.published())

        brand.mark_published()

        self.assertNotIn(brand, Brand.objects.under_revision())
        self.assertIn(brand, Brand.objects.published())

    def test_mark_published_save_false_does_not_touch_db(self):
        brand = Brand.objects.create(name="PRS")
        brand.mark_published(save=False)
        # In-memory object is updated...
        self.assertEqual(brand.status, PublicationStatus.PUBLISHED)
        self.assertIsNotNone(brand.published_at)
        # ...but the DB row is untouched.
        reloaded = Brand.objects.get(pk=brand.pk)
        self.assertEqual(reloaded.status, PublicationStatus.UNDER_REVISION)
        self.assertIsNone(reloaded.published_at)

    def test_mark_published_bumps_updated_at(self):
        brand = Brand.objects.create(name="Charvel")
        original_updated = brand.updated_at
        # Force a measurable gap so auto_now produces a strictly later value.
        Brand.objects.filter(pk=brand.pk).update(
            updated_at=timezone.now() - timedelta(hours=1)
        )
        brand.refresh_from_db()
        stale_updated = brand.updated_at
        self.assertLess(stale_updated, original_updated)

        brand.mark_published()
        brand.refresh_from_db()
        self.assertGreater(brand.updated_at, stale_updated)


# ---------------------------------------------------------------------------
# GearItem.__str__ == "<brand> <name>"
# ---------------------------------------------------------------------------
class GearStrTests(TestCase):
    """Every concrete GearItem renders as "<brand> <name>" (Brand.__str__ is its
    name), across all four gear types."""

    def setUp(self):
        self.brand = Brand.objects.create(
            name="Seymour Duncan", status=PublicationStatus.PUBLISHED
        )

    def test_bridge_str(self):
        bridge_type = BridgeType.objects.create(name="Floyd Rose", is_tremolo=True)
        bridge = Bridge.objects.create(
            brand=self.brand, name="1000 Series", bridge_type=bridge_type
        )
        self.assertEqual(str(bridge), "Seymour Duncan 1000 Series")

    def test_pickup_str(self):
        pickup_type = PickupType.objects.create(name="Humbucker", symbol="H")
        pickup = Pickup.objects.create(
            brand=self.brand, name="JB SH-4", pickup_type=pickup_type
        )
        self.assertEqual(str(pickup), "Seymour Duncan JB SH-4")

    def test_tuner_str(self):
        tuner = Tuner.objects.create(brand=self.brand, name="Locking Tuners")
        self.assertEqual(str(tuner), "Seymour Duncan Locking Tuners")

    def test_nut_str(self):
        nut_material = NutMaterial.objects.create(name="Bone")
        nut = Nut.objects.create(
            brand=self.brand, name="Standard Nut", material=nut_material
        )
        self.assertEqual(str(nut), "Seymour Duncan Standard Nut")

    def test_str_uses_brand_str_not_id(self):
        # The format embeds the Brand object, whose __str__ is its name — so the
        # rendered string must contain the brand NAME, never a pk/repr.
        other_brand = Brand.objects.create(name="DiMarzio")
        pickup_type = PickupType.objects.create(name="Single Coil", symbol="S")
        pickup = Pickup.objects.create(
            brand=other_brand, name="Area 67", pickup_type=pickup_type
        )
        self.assertEqual(str(pickup), "DiMarzio Area 67")
        self.assertNotIn(str(other_brand.pk), str(pickup))

    def test_str_reflects_name_change(self):
        tuner = Tuner.objects.create(brand=self.brand, name="Old Name")
        tuner.name = "New Name"
        self.assertEqual(str(tuner), "Seymour Duncan New Name")


# ---------------------------------------------------------------------------
# GuitarModel.scale_display (single value vs multiscale range)
# ---------------------------------------------------------------------------
class GuitarScaleDisplayTests(TestCase):
    """scale_display trims trailing zeros and renders a single value (min==max)
    or an en-dash range (min!=max)."""

    @classmethod
    def setUpTestData(cls):
        cls.brand = Brand.objects.create(
            name="Display Brand", status=PublicationStatus.PUBLISHED
        )

    def _guitar(self, lo, hi, *, num_strings=6):
        return GuitarModel(
            brand=self.brand,
            name="Test",
            num_strings=num_strings,
            scale_length_min_inches=Decimal(lo),
            scale_length_max_inches=Decimal(hi),
        )

    def test_single_scale_whole_number_trims_all_zeros(self):
        # 25.000 -> '25"'
        guitar = self._guitar("25.000", "25.000")
        self.assertEqual(guitar.scale_display, '25"')

    def test_single_scale_one_decimal(self):
        # 25.500 -> '25.5"'
        guitar = self._guitar("25.500", "25.500")
        self.assertEqual(guitar.scale_display, '25.5"')

    def test_single_scale_two_decimals(self):
        # 24.750 -> '24.75"'  (the famous Gibson scale)
        guitar = self._guitar("24.750", "24.750")
        self.assertEqual(guitar.scale_display, '24.75"')

    def test_single_scale_no_trailing_dot(self):
        # The trim must never leave a dangling decimal point.
        guitar = self._guitar("25.000", "25.000")
        self.assertNotIn(".", guitar.scale_display)
        self.assertFalse(guitar.scale_display.rstrip('"').endswith("."))

    def test_multiscale_renders_endash_range(self):
        # min != max -> 'lo–hi"' using an EN DASH (U+2013), not a hyphen.
        guitar = self._guitar("25.500", "27.000", num_strings=7)
        self.assertEqual(guitar.scale_display, '25.5–27"')
        self.assertIn("–", guitar.scale_display)

    def test_multiscale_both_endpoints_trimmed_independently(self):
        # 25.500 -> '25.5', 26.500 -> '26.5'
        guitar = self._guitar("25.500", "26.500", num_strings=8)
        self.assertEqual(guitar.scale_display, '25.5–26.5"')

    def test_multiscale_mixed_precision_endpoints(self):
        # lo trims to whole, hi keeps two decimals.
        guitar = self._guitar("25.000", "26.750", num_strings=7)
        self.assertEqual(guitar.scale_display, '25–26.75"')

    def test_multiscale_uses_endash_not_hyphen(self):
        # Explicitly guard against a plain ASCII hyphen sneaking in.
        guitar = self._guitar("24.750", "25.500", num_strings=6)
        self.assertNotIn("-", guitar.scale_display)

    def test_equal_min_max_with_decimals_is_single_value(self):
        # Numerically-equal endpoints (with explicit places) collapse to single.
        guitar = self._guitar("24.750", "24.750")
        self.assertEqual(guitar.scale_display, '24.75"')
        self.assertNotIn("–", guitar.scale_display)

    def test_scale_display_always_ends_with_quote(self):
        for lo, hi in [("25.000", "25.000"), ("25.500", "27.000")]:
            guitar = self._guitar(lo, hi, num_strings=7)
            self.assertTrue(guitar.scale_display.endswith('"'))

    def test_scale_display_persisted_guitar(self):
        # Behaviour is identical for a saved instance (it's a pure property over
        # two columns, but verify there's no save-time surprise).
        guitar = self._guitar("24.750", "24.750")
        guitar.save()
        guitar.refresh_from_db()
        self.assertEqual(guitar.scale_display, '24.75"')

    def test_guitar_str_is_brand_then_name(self):
        # GuitarModel shares the "<brand> <name>" __str__ convention.
        guitar = self._guitar("25.500", "25.500")
        guitar.name = "Custom 24"
        self.assertEqual(str(guitar), "Display Brand Custom 24")

    def test_is_multiscale_flag_matches_display_for_range(self):
        # The display-as-range condition (min != max) is the SAME predicate the
        # derived is_multiscale facet uses, so they must agree.
        single = self._guitar("25.500", "25.500")
        multi = self._guitar("25.500", "27.000", num_strings=7)
        self.assertEqual(single.compute_derived()["is_multiscale"], False)
        self.assertEqual(multi.compute_derived()["is_multiscale"], True)
        self.assertNotIn("–", single.scale_display)
        self.assertIn("–", multi.scale_display)
