# Generated by Django 6.0.6 on 2026-06-13 19:21

import django.db.models.deletion
import django.utils.timezone
import forum.models.engagement
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('activity_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['-activity_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_market', models.BooleanField(default=False)),
                ('requires_disclaimer', models.BooleanField(default=False)),
                ('is_predefined', models.BooleanField(default=False)),
                ('activity_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['-activity_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketDisclaimerAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_disclaimer_acceptance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market disclaimer acceptance',
                'verbose_name_plural': 'Market disclaimer acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='External video link only (e.g. YouTube).')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('activity_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.subtopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='External video link only (e.g. YouTube).')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubtopicProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_name', models.CharField(max_length=100)),
                ('proposed_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closes_at', models.DateTimeField()),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('parent_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_proposals', to='forum.topic')),
            ],
            options={
                'ordering': ['-opened_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='forum.topic'),
        ),
        migrations.CreateModel(
            name='TopicProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_name', models.CharField(max_length=100)),
                ('proposed_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closes_at', models.DateTimeField()),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(choices=[(1, 'For'), (-1, 'Against')])),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_proposal_votes', to=settings.AUTH_USER_MODEL)),
                ('subtopic_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.subtopicproposal')),
                ('topic_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.topicproposal')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.IntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='forum/', validators=[forum.models.engagement.validate_forum_image])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='forum_attac_content_223ca5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('emoji', models.CharField(max_length=8)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='forum_react_content_81dc1b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id', 'emoji'), name='unique_reaction_per_user_target_emoji')],
            },
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(fields=('topic', 'slug'), name='unique_subtopic_slug_per_topic'),
        ),
        migrations.AddConstraint(
            model_name='proposalvote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('subtopic_proposal__isnull', True), ('topic_proposal__isnull', False)), models.Q(('subtopic_proposal__isnull', False), ('topic_proposal__isnull', True)), _connector='OR'), name='proposalvote_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='proposalvote',
            constraint=models.UniqueConstraint(condition=models.Q(('topic_proposal__isnull', False)), fields=('voter', 'topic_proposal'), name='unique_vote_per_voter_per_topic_proposal'),
        ),
        migrations.AddConstraint(
            model_name='proposalvote',
            constraint=models.UniqueConstraint(condition=models.Q(('subtopic_proposal__isnull', False)), fields=('voter', 'subtopic_proposal'), name='unique_vote_per_voter_per_subtopic_proposal'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['content_type', 'object_id'], name='forum_vote_content_bbf619_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'content_type', 'object_id'), name='unique_vote_per_voter_per_target'),
        ),
    ]
