# Generated by Django 6.0.6 on 2026-06-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_is_removed_comment_removal_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(max_length=32),
        ),
    ]
