# Generated by Django 6.0.6 on 2026-06-14 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='silence',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='silences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warning',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
