# Generated by Django 6.0.6 on 2026-06-14 03:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_correction_reviewvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarmodel',
            name='scale_length_max_inches',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='scale_length_min_inches',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
