# Generated by Django 6.0.6 on 2026-06-14 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_guitarmodel_scale_length_max_inches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarmodel',
            name='num_frets',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='num_strings',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
