# Generated by Django 6.0.6 on 2026-06-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_guitarmodel_num_frets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarmodel',
            name='body_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.bodymaterial'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='body_shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.bodyshape'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.bridge'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.country'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='fret_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.fretmaterial'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='fretboard_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.fretboardmaterial'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='fretboard_radius',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.fretboardradius'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='headstock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.headstocktype'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='neck_construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.neckconstruction'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='neck_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.neckmaterial'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='neck_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.neckprofile'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='nut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.nut'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='selector_switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.selectorswitch'),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='tuners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guitars', to='catalog.tuner'),
        ),
    ]
