# Generated by Django 6.0.6 on 2026-06-14 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_guitarmodel_body_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='correction',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guitarmodel',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nut',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tuner',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
